export const specializations = [
  "Cardiology",
  "Dermatology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Gynecology",
  "Oncology",
  "Psychiatry",
  "Ophthalmology",
  "ENT",
  "Endocrinology",
  "Gastroenterology",
  "Nephrology",
  "Pulmonology",
  "Urology",
  "Rheumatology",
  "Hematology",
  "Anesthesiology",
  "Radiology",
  "Pathology",
  "General Surgery",
  "Plastic Surgery",
];
